name: MCDeceit
main: site.pegasis.mc.deceit.Main
version: "1.0"
api-version: "1.15"
depend: [HolographicDisplays,
         ProtocolLib,
         LightAPI]
commands:
  start-deciet:
    description: Start deciet game.
    usage: /<command>
    permission: mcdeceit.start
    permission-message: You don't have <permission>
  light-on:
    description: light on
    usage: /<command>
    permission: mcdeceit.start
    permission-message: You don't have <permission>
  light-off:
    description: light off.
    usage: /<command>
    permission: mcdeceit.start
    permission-message: You don't have <permission>
  debug-deceit:
    description: debug
    usage: /<command>
    permission: mcdeceit.start
    permission-message: You don't have <permission>
